mod appearance;
mod close;
mod decorations;
pub(crate) mod fixture;
mod fullscreen;
mod globals;
mod initial_configure;
mod layers;
mod lifecycle;
mod pointer_focus;
mod popups;
mod presentation;
mod redraw;
mod tiling;
mod wire;
mod workspaces;
