mod compositor;
mod cursor_shape;
mod decorations;
pub(crate) use decorations::kde::KdeDecorations;
pub(crate) mod dmabuf;
mod layer_shell;
mod output;
mod pointer_constraints;
mod presentation;
mod relative_pointer;
mod seat;
mod selection;
mod shm;
mod viewport;
pub(crate) mod workspace;
mod xdg;
